<?php

namespace ContainerQZozus4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HDz1GZNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hDz1GZN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hDz1GZN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'series' => ['privates', '.errored..service_locator.hDz1GZN.App\\Entity\\Series', NULL, 'Cannot autowire service ".service_locator.hDz1GZN": it references class "App\\Entity\\Series" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'series' => 'App\\Entity\\Series',
        ]);
    }
}
