<?php

namespace ContainerF1Zvf4t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NN2UnFPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nN2UnFP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nN2UnFP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'series' => ['privates', '.errored..service_locator.nN2UnFP.App\\Entity\\Series', NULL, 'Cannot autowire service ".service_locator.nN2UnFP": it references class "App\\Entity\\Series" but no such service exists.'],
        ], [
            'series' => 'App\\Entity\\Series',
        ]);
    }
}
