<?php

namespace ContainerF1Zvf4t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BV2R6kCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BV2R6kC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BV2R6kC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\SerieController::delete' => ['privates', '.service_locator.hDz1GZN', 'get_ServiceLocator_HDz1GZNService', true],
            'App\\Controller\\SerieController::edit' => ['privates', '.service_locator.hDz1GZN', 'get_ServiceLocator_HDz1GZNService', true],
            'App\\Controller\\SerieController::index' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\SerieController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\SerieController::show' => ['privates', '.service_locator.nN2UnFP', 'get_ServiceLocator_NN2UnFPService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\SerieController:delete' => ['privates', '.service_locator.hDz1GZN', 'get_ServiceLocator_HDz1GZNService', true],
            'App\\Controller\\SerieController:edit' => ['privates', '.service_locator.hDz1GZN', 'get_ServiceLocator_HDz1GZNService', true],
            'App\\Controller\\SerieController:index' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\SerieController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\SerieController:show' => ['privates', '.service_locator.nN2UnFP', 'get_ServiceLocator_NN2UnFPService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\SerieController::delete' => '?',
            'App\\Controller\\SerieController::edit' => '?',
            'App\\Controller\\SerieController::index' => '?',
            'App\\Controller\\SerieController::new' => '?',
            'App\\Controller\\SerieController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\SerieController:delete' => '?',
            'App\\Controller\\SerieController:edit' => '?',
            'App\\Controller\\SerieController:index' => '?',
            'App\\Controller\\SerieController:new' => '?',
            'App\\Controller\\SerieController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
