<?php

namespace ContainerF1Zvf4t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hDz1GZN.App\Entity\Series' shared service.
     *
     * @return \App\Entity\Series
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hDz1GZN": it references class "App\\Entity\\Series" but no such service exists.');
    }
}
